config:
  target: "http://localhost:8010"
  phases:
    - duration: 30
      arrivalRate: 100
      name: Required minimum load
    - duration: 60
      arrivalRate: 100
      rampTo: 500
      name: Higher load tests
  ensure:
    p95: 200
    maxErrorRate: 1